### ISSUE TITLE
SearXNG metasearch engine support

### ISSUE THREAD

**Issue by devxan** [mjysci/linkwarden-search#1]
Hello! Thank you for making this and sharing it [here](https://github.com/linkwarden/linkwarden/issues/794)!

The [linkding-injector](https://github.com/Fivefold/linkding-injector) extension supports [SearXNG](https://searxng.org/) with [this URL pattern](https://github.com/Fivefold/linkding-injector/wiki/SearX-SearXNG-support), and that's the search engine I use. Is this possible to add support for in a userscript? (Could you add SearXNG support?)

**Comment by mjysci** [comment]
[Done](https://github.com/mjysci/linkwarden-search/commit/dd3bdeb0d8e29f6d39b00888e7cf24c031ba1a47). You have to use other search engine (like Google) once to open the setting, enabled the SearXNG support, since it's disable on default.  
It's been tested on:
https://search.inetol.net/
https://search.indst.eu/
